id: IC7171650
legacy_id: P010590
ocr_import_info:
  bdrc_scan_id: W9209
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T04:55:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:06:42.140937+00:00'
last_modified: 2022-09-04 13:09:30.265717
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W9209
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW9209
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁའ་འགྲོ་གསང་བ་ཡེ་ཤེས་ཀྱི་ཆོས་སྐོར།
  author: འོལ་དགའ་རྗེ་དྲུང ༠༣་བཞད་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7956975191983399
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I3090:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3090
      total_pages: 584
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3090.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8234330955401223
    legacy_id: v008
  I3094:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3094
      total_pages: 536
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3094.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7618904138144205
    legacy_id: v012
  I3084:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3084
      total_pages: 652
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3084.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7951997181271667
    legacy_id: v002
  I3091:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3091
      total_pages: 508
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3091.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7874085196678179
    legacy_id: v009
  I3087:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3087
      total_pages: 526
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3087.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8248178213659989
    legacy_id: v005
  I3083:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3083
      total_pages: 740
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3083.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8032131453433682
    legacy_id: v001
  I3093:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3093
      total_pages: 486
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3093.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7808396965369924
    legacy_id: v011
  I3086:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3086
      total_pages: 524
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3086.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.810357491887063
    legacy_id: v004
  I3085:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3085
      total_pages: 602
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3085.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7534619386262911
    legacy_id: v003
  I3095:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3095
      total_pages: 566
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I3095.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7627124448866555
    legacy_id: v013
  I3098:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3098
      total_pages: 448
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I3098.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7779242394418029
    legacy_id: v016
  I3096:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3096
      total_pages: 444
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I3096.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7248538284337417
    legacy_id: v014
  I3092:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3092
      total_pages: 506
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3092.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8111563815158667
    legacy_id: v010
  I3089:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3089
      total_pages: 526
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3089.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8416493306425501
    legacy_id: v007
  I3097:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3097
      total_pages: 412
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I3097.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7801507134171092
    legacy_id: v015
  I3088:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3088
      total_pages: 888
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3088.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8275397976930491
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
